CREATE TABLE ApplicationUserRoles (
 Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
 UserId NVARCHAR(450) NOT NULL,
 Name NVARCHAR(256) NOT NULL,
 CONSTRAINT FK_UserRoles_User FOREIGN KEY (UserId) REFERENCES dbo.ApplicationUsers(Id) ON DELETE CASCADE
 )