CREATE TABLE ApplicationUsers (
    Id NVARCHAR(450) PRIMARY KEY NOT NULL,
    UserName NVARCHAR(120) NOT NULL,
	Email NVARCHAR(256) NOT NULL,
    ProfileImage VARBINARY(MAX) NOT NULL DEFAULT (0x),
	ProfileImagePath NVARCHAR(MAX) NOT NULL DEFAULT '',
	CreatedAt DATETIME DEFAULT GETDATE() NOT NULL,
	UpdatedAt DATETIME DEFAULT GETDATE() NOT NULL
);