CREATE TABLE Member (
    MemberId UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(), 
    UserId NVARCHAR(450) NOT NULL,  
    RoomId UNIQUEIDENTIFIER NOT NULL,  
    Role NVARCHAR(50) NOT NULL DEFAULT 'member', 
    JoinedAt DATETIME NOT NULL DEFAULT GETDATE(),
    CONSTRAINT FK_Member_UserId FOREIGN KEY (UserId) REFERENCES ApplicationUsers(Id) ON DELETE CASCADE,
    CONSTRAINT FK_Member_RoomId FOREIGN KEY (RoomId) REFERENCES Room(RoomId) ON DELETE CASCADE,
	CONSTRAINT FK_Member_ValidRole FOREIGN KEY (Role) REFERENCES ValidMemberRoles(Role) ON DELETE CASCADE
);
