CREATE TABLE ApplicationUser (
    Id VARCHAR(450) PRIMARY KEY NOT NULL,
    UserName NVARCHAR(120) NOT NULL,
	Email NVARCHAR(256) NOT NULL,
	PasswordHash NVARCHAR(MAX) NOT NULL,
    ProfileImage VARBINARY(MAX) NOT NULL DEFAULT (0x),
	ProfileImageUrl NVARCHAR(MAX) NOT NULL DEFAULT '',
	CreatedAt DATETIME DEFAULT GETDATE() NOT NULL,
	UpdatedAt DATETIME DEFAULT GETDATE() NOT NULL
);